sudo: required

services:
- docker

script:
- docker build -t wisecloud/openresty:$TRAVIS_BRANCH .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wisecloud/openresty:$TRAVIS_BRANCH
  on:
    all_branches: true
    #condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
