sudo: required

services:
- docker


script:
#- RESTY_VERSION="1.13.6.2"
- RESTY_VERSION="1.15.8.1"
- docker build -t wisecloud/openresty:$RESTY_VERSION .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wisecloud/openresty:$RESTY_VERSION
  on:
    all_branches: true
